version: "3"
services:
  push-notification-server:
    container_name: "talk-push-proxy"
    build: docker/.
    ports:
      - '8066:8066'
    volumes:
      - ./:/talk-push-proxy/
    networks:
      - skymail-docker

networks:
  skymail-docker:
    external:
      name: skymail-docker